-- Add metadata columns to competitions
ALTER TABLE competitions
    ADD COLUMN region       VARCHAR(100),
    ADD COLUMN level        VARCHAR(50),
    ADD COLUMN location     VARCHAR(200),
    ADD COLUMN comp_season  VARCHAR(20),
    ADD COLUMN is_preset    BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN states       VARCHAR(100);  -- comma-separated 2-letter state codes; NULL = national

-- ── Preset leagues ────────────────────────────────────────────────────────────
INSERT INTO competitions (name, type, region, level, is_preset, states) VALUES
('MLS NEXT',                          'LEAGUE', 'National',        'Elite',            true, NULL),
('ECNL',                              'LEAGUE', 'National',        'Elite',            true, NULL),
('Girls Academy',                     'LEAGUE', 'National',        'Elite',            true, NULL),
('National Academy League',           'LEAGUE', 'National',        'Elite',            true, NULL),
('USYS National League',              'LEAGUE', 'National',        'Elite',            true, NULL),
('National Premier Leagues',          'LEAGUE', 'National',        'Elite',            true, NULL),
('USL Academy',                       'LEAGUE', 'National',        'Elite',            true, NULL),
('EDP Soccer',                        'LEAGUE', 'NJ/NY/PA/CT',     'Competitive',      true, 'NJ,NY,PA,CT'),
('EDP Futures',                       'LEAGUE', 'NJ/NY/PA/CT',     'Developmental',    true, 'NJ,NY,PA,CT'),
('EDP Championship',                  'LEAGUE', 'NJ/NY/PA/CT',     'Competitive',      true, 'NJ,NY,PA,CT'),
('EDP Premier',                       'LEAGUE', 'NJ/NY/PA/CT',     'High Competitive', true, 'NJ,NY,PA,CT'),
('ICSL',                              'LEAGUE', 'NY/NJ',           'Competitive',      true, 'NY,NJ'),
('Cosmopolitan Junior Soccer League', 'LEAGUE', 'NY',              'Competitive',      true, 'NY'),
('Long Island Junior Soccer League',  'LEAGUE', 'NY',              'Competitive',      true, 'NY'),
('Connecticut Junior Soccer Association','LEAGUE','CT',            'Competitive',      true, 'CT');

-- ── Preset tournaments ────────────────────────────────────────────────────────
INSERT INTO competitions (name, type, location, comp_season, is_preset, states) VALUES
-- New Jersey
('EDP Summer Sizzler',               'TOURNAMENT', 'New Jersey',           'Summer', true, 'NJ'),
('EDP Fall Kickoff',                 'TOURNAMENT', 'New Jersey',           'Fall',   true, 'NJ'),
('EDP Cup Spring Showcase',          'TOURNAMENT', 'New Jersey',           'Spring', true, 'NJ'),
('PDA Showcase',                     'TOURNAMENT', 'Somerset, NJ',         'Spring', true, 'NJ'),
('NJYS State Cup',                   'TOURNAMENT', 'New Jersey',           'Spring', true, 'NJ'),
('NJYS Open Cup',                    'TOURNAMENT', 'New Jersey',           'Spring', true, 'NJ'),
('Iron Peak Spring Kickoff',         'TOURNAMENT', 'Hillsborough, NJ',     'Spring', true, 'NJ'),
('Iron Peak Ice Breaker',            'TOURNAMENT', 'Hillsborough, NJ',     'Winter', true, 'NJ'),
('Manalapan Memorial Day Tournament','TOURNAMENT', 'Manalapan, NJ',        'Spring', true, 'NJ'),
('Manalapan Summer Kickoff',         'TOURNAMENT', 'Manalapan, NJ',        'Summer', true, 'NJ'),
('STA Spring Invitational',          'TOURNAMENT', 'New Jersey',           'Spring', true, 'NJ'),
('Match Fit Cup',                    'TOURNAMENT', 'New Jersey',           'Summer', true, 'NJ'),
('FC Copa Invitational',             'TOURNAMENT', 'New Jersey',           'Summer', true, 'NJ'),
('Morris United Cup',                'TOURNAMENT', 'New Jersey',           'Summer', true, 'NJ'),
('Jersey Shore Champions Cup',       'TOURNAMENT', 'Ocean Township, NJ',   'Summer', true, 'NJ'),
('Coastal Cup Summer Classic',       'TOURNAMENT', 'Hillsborough, NJ',     'Summer', true, 'NJ'),
('Central Jersey Invitational',      'TOURNAMENT', 'East Brunswick, NJ',   'Summer', true, 'NJ'),
('Mt Olive Cup',                     'TOURNAMENT', 'New Jersey',           'Summer', true, 'NJ'),
('Neptune Summer Kickoff',           'TOURNAMENT', 'New Jersey',           'Summer', true, 'NJ'),
('Sunburst Tournament',              'TOURNAMENT', 'West Windsor, NJ',     'Summer', true, 'NJ'),
('Cherry Hill FC Summer Classic',    'TOURNAMENT', 'Cherry Hill, NJ',      'Summer', true, 'NJ'),
('Beach Blast',                      'TOURNAMENT', 'Wildwood, NJ',         'Summer', true, 'NJ'),
('Wall Summer Classic',              'TOURNAMENT', 'Wall, NJ',             'Summer', true, 'NJ'),
('Ocean Cup',                        'TOURNAMENT', 'New Jersey',           'Summer', true, 'NJ'),
('Cedar Stars Academy Invitational', 'TOURNAMENT', 'New Jersey',           'Summer', true, 'NJ'),
-- Pennsylvania
('Penn Fusion Summer Classic',       'TOURNAMENT', 'West Chester, PA',     'Summer', true, 'PA'),
('FC Delco Players Cup',             'TOURNAMENT', 'Pennsylvania',         'Spring', true, 'PA'),
('FC Delco Fall Showcase',           'TOURNAMENT', 'Pennsylvania',         'Fall',   true, 'PA'),
('PA Classics Mid-Atlantic Cup',     'TOURNAMENT', 'Manheim, PA',          'Spring', true, 'PA'),
('Hershey Memorial Day Challenge',   'TOURNAMENT', 'Hershey, PA',          'Spring', true, 'PA'),
('Hershey Summer Classic',           'TOURNAMENT', 'Hershey, PA',          'Summer', true, 'PA'),
('Lancaster Summer Classic',         'TOURNAMENT', 'Pennsylvania',         'Summer', true, 'PA'),
('Philadelphia Union Summer Bash',   'TOURNAMENT', 'Pennsylvania',         'Summer', true, 'PA'),
('Philly Summer Shootout',           'TOURNAMENT', 'Pennsylvania',         'Summer', true, 'PA'),
('CRUSA Invitational',               'TOURNAMENT', 'Pennsylvania',         'Summer', true, 'PA'),
('LVYSL Tournament',                 'TOURNAMENT', 'Allentown, PA',        'Summer', true, 'PA'),
('Reading Rage Flash Tournament',    'TOURNAMENT', 'Pennsylvania',         'Summer', true, 'PA'),
('Whitpain Spring Classic',          'TOURNAMENT', 'Pennsylvania',         'Spring', true, 'PA'),
('York Cup White Rose Classic',      'TOURNAMENT', 'Pennsylvania',         'Summer', true, 'PA'),
('Lititz Summer Showcase',           'TOURNAMENT', 'Pennsylvania',         'Summer', true, 'PA'),
('7v7 July Jamboree',                'TOURNAMENT', 'Manheim, PA',          'Summer', true, 'PA'),
-- New York
('East Meadow Memorial Day Tournament',             'TOURNAMENT', 'New York',   'Spring', true, 'NY'),
('Long Island Classic Memorial Day Tournament',     'TOURNAMENT', 'New York',   'Spring', true, 'NY'),
('Massapequa Memorial Day Tournament',              'TOURNAMENT', 'New York',   'Spring', true, 'NY'),
('RNY FC Cup and College Showcase',                 'TOURNAMENT', 'New York',   'Summer', true, 'NY'),
('Salt City Cup',                    'TOURNAMENT', 'Syracuse, NY',         'Summer', true, 'NY'),
('Chili Invitational',               'TOURNAMENT', 'Rochester, NY',        'Summer', true, 'NY'),
('High Peaks Cup',                   'TOURNAMENT', 'Lake Placid, NY',      'Summer', true, 'NY'),
('Manhattan Kickoff Classic',        'TOURNAMENT', 'New York',             'Spring', true, 'NY'),
('New York Surf Challenge Cup',      'TOURNAMENT', 'New York',             'Summer', true, 'NY'),
-- Connecticut
('Oakwood Invitational',             'TOURNAMENT', 'Connecticut',          'Summer', true, 'CT'),
('Beachside Invitational',           'TOURNAMENT', 'Connecticut',          'Summer', true, 'CT'),
('CFC Showcase',                     'TOURNAMENT', 'Connecticut',          'Summer', true, 'CT'),
('Connecticut Rush Tournament',      'TOURNAMENT', 'Connecticut',          'Summer', true, 'CT'),
('FSA FC Showcase',                  'TOURNAMENT', 'Connecticut',          'Summer', true, 'CT'),
-- Other
('Jefferson Cup',                    'TOURNAMENT', 'Virginia',             'Spring', true, 'VA'),
('Surf Cup East',                    'TOURNAMENT', 'East Coast',           'Summer', true, NULL),
('Disney Showcase',                  'TOURNAMENT', 'Florida',              'Winter', true, 'FL');
