-- V6: Registration-code-based onboarding and player registration requests

-- ─────────────────────────────────────────
-- registration_codes
-- Codes generated by ADMIN users to invite COACHes or PARENTs to a specific team.
-- ─────────────────────────────────────────
CREATE TABLE registration_codes (
    id                  BIGSERIAL    PRIMARY KEY,
    code                VARCHAR(64)  NOT NULL,
    team_id             BIGINT       NOT NULL REFERENCES teams (id),
    role                VARCHAR(50)  NOT NULL,
    active              BOOLEAN      NOT NULL DEFAULT TRUE,
    expires_at          TIMESTAMPTZ,
    max_uses            INTEGER,
    uses_count          INTEGER      NOT NULL DEFAULT 0,
    created_by_user_id  BIGINT       NOT NULL REFERENCES users (id),
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_registration_codes_code UNIQUE (code),
    CONSTRAINT chk_rc_uses_count CHECK (uses_count >= 0)
);

CREATE INDEX idx_rc_code    ON registration_codes (code);
CREATE INDEX idx_rc_team_id ON registration_codes (team_id);
CREATE INDEX idx_rc_active  ON registration_codes (active);

-- ─────────────────────────────────────────
-- user_team_memberships
-- Tracks which team(s) a PARENT user is associated with.
-- Created when a PARENT registers via a team-scoped registration code.
-- ─────────────────────────────────────────
CREATE TABLE user_team_memberships (
    id      BIGSERIAL PRIMARY KEY,
    user_id BIGINT    NOT NULL REFERENCES users (id),
    team_id BIGINT    NOT NULL REFERENCES teams (id),
    CONSTRAINT uq_utm_user_team UNIQUE (user_id, team_id)
);

CREATE INDEX idx_utm_user_id ON user_team_memberships (user_id);
CREATE INDEX idx_utm_team_id ON user_team_memberships (team_id);

-- ─────────────────────────────────────────
-- player_registration_requests
-- Submitted by PARENT users; approved by ADMIN, which creates Player + ParentPlayerRelationship.
-- ─────────────────────────────────────────
CREATE TABLE player_registration_requests (
    id                   BIGSERIAL    PRIMARY KEY,
    parent_user_id       BIGINT       NOT NULL REFERENCES users (id),
    team_id              BIGINT       NOT NULL REFERENCES teams (id),
    first_name           VARCHAR(100) NOT NULL,
    last_name            VARCHAR(100) NOT NULL,
    date_of_birth        DATE         NOT NULL,
    primary_position     VARCHAR(10)  NOT NULL,
    secondary_position   VARCHAR(10),
    strong_foot          VARCHAR(10),
    jersey_number        INTEGER      CHECK (jersey_number BETWEEN 1 AND 99),
    status               VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    reviewed_by_user_id  BIGINT       REFERENCES users (id),
    reviewed_at          TIMESTAMPTZ,
    rejection_reason     VARCHAR(500),
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_prr_parent_user_id ON player_registration_requests (parent_user_id);
CREATE INDEX idx_prr_status         ON player_registration_requests (status);
CREATE INDEX idx_prr_team_id        ON player_registration_requests (team_id);
